import mapData from '../../server/db/json/map.json'
import WorldMapper from './Explore/WorldMapper'

function WorldMap() {
  console.log(mapData)
  return (
    <div className="world-map">
      <WorldMapper />
    </div>
  )
}

export default WorldMap

/* <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="map.jpg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Sandy Cove" title="Sandy Cove" href="/sandy-cove" coords="752,619,94" shape="circle">
    <area target="" alt="Everdew Woods" title="Everdew Woods" href="/everdew-woods" coords="711,880,461,1036" shape="rect">
    <area target="" alt="Umbral Marshes" title="Umbral Marshes" href="/umbral-marshes" coords="907,915,120" shape="circle">
    <area target="" alt="Bellston" title="Bellston" href="/bellston" coords="441,652,83" shape="circle">
    <area target="" alt="Echoing Caves" title="Echoing Caves" href="/echoing-caves" coords="498,783,48" shape="circle">
    <area target="" alt="Port Wunder" title="Port Wunder" href="/port-wunder" coords="929,716,69" shape="circle">
    <area target="" alt="The Fair Mistral" title="The Fair Mistral" href="/the-fair-mistral" coords="971,563,75" shape="circle">
    <area target="" alt="Freefolk Foothills" title="Freefolk Foothills" href="/freefolk-foothills" coords="688,1178,119" shape="circle">
    <area target="" alt="Lavender Oasis" title="Lavender Oasis" href="/lavender-oasis" coords="1153,1190,87" shape="circle">
    <area target="" alt="Isle of Crimson" title="Isle of Crimson" href="/isle-of-crimson" coords="1405,584,194" shape="circle">
    <area target="" alt="Boreal Peaks" title="Boreal Peaks" href="/boreal-peaks" coords="484,306,893,461" shape="rect">
    <img src="/Images/map.jpg" alt="" />
    map={{ name: 'world-map', areas: mapData }}
</map> */
